modLoader="javafml"
loaderVersion="[60,)"
license="MIT"

[[mods]]
modId="worldsupervisor"
version="${file.jarVersion}"
displayName="World Supervisor"
description="Process supervisor for Minecraft Forge server"

[[dependencies.worldsupervisor]]
modId="forge"
mandatory=true
versionRange="[60,)"
ordering="NONE"
side="SERVER"

[[dependencies.worldsupervisor]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="SERVER"
