name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build
        run: |
          ./gradlew genIntellijRuns
          ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: world-supervisor-forge
          path: build/libs/*.jar
